SELECT t2.AUTHOR_ID, t2.AUTHOR_NAME, t2.CATEGORY, SUM(t1.SALES * t2.PRICE) AS TOTAL_SALES
FROM BOOK_SALES t1 RIGHT OUTER JOIN
    (SELECT b.BOOK_ID, b.CATEGORY, a.AUTHOR_ID, a.AUTHOR_NAME, b.PRICE
    FROM BOOK b LEFT OUTER JOIN AUTHOR a
    ON a.AUTHOR_ID = b.AUTHOR_ID) t2
ON t1.BOOK_ID = t2.BOOK_ID
WHERE YEAR(t1.SALES_DATE) = 2022 AND MONTH(t1.SALES_DATE) = 1
GROUP BY t2.AUTHOR_ID, t2.AUTHOR_NAME, t2.CATEGORY
ORDER BY t2.AUTHOR_ID, t2.CATEGORY DESC;