SELECT m.ITEM_ID, i.ITEM_NAME,	i.RARITY
FROM ITEM_TREE m INNER JOIN ITEM_INFO i
ON i.ITEM_ID = m.ITEM_ID
WHERE NOT EXISTS 
    (SELECT ITEM_ID 
    FROM ITEM_TREE s
    WHERE m.ITEM_ID = s.PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC