# -- 코드를 입력하세요
# (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT  FROM ONLINE_SALE WHERE SALES_DATE LIKE "2022-03-%")
# (SELECT SALES_DATE, PRODUCT_ID,SALES_AMOUNT FROM OFFLINE_SALE WHERE SALES_DATE LIKE "2022-03%")

# SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT  FROM (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT  FROM ONLINE_SALE WHERE SALES_DATE LIKE "2022-03-%")ONLINE_SALE INNER JOIN (SELECT SALES_DATE, PRODUCT_ID,SALES_AMOUNT FROM OFFLINE_SALE WHERE SALES_DATE LIKE "2022-03%")OFFLINE_SALE
# WHERE SALES_DATE LIKE "2022-03-%"
# SELECT 
#     COALESCE(o.SALES_DATE, f.SALES_DATE) AS SALES_DATE, 
#     COALESCE(o.PRODUCT_ID, f.PRODUCT_ID) AS PRODUCT_ID, 
#     o.USER_ID, 
#     COALESCE(o.SALES_AMOUNT, f.SALES_AMOUNT) AS SALES_AMOUNT
# FROM 
#     (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT  
#      FROM ONLINE_SALE 
#      WHERE SALES_DATE LIKE '2022-03-%') AS o
# FULL OUTER JOIN 
#     (SELECT SALES_DATE, PRODUCT_ID, SALES_AMOUNT 
#      FROM OFFLINE_SALE 
#      WHERE SALES_DATE LIKE '2022-03-%') AS f
# ON 
#     o.SALES_DATE = f.SALES_DATE 
#     AND o.PRODUCT_ID = f.PRODUCT_ID;
SELECT 
    date_format(SALES_DATE, '%Y-%m-%d')AS SALES_DATE, 
    PRODUCT_ID, 
    USER_ID, 
    SALES_AMOUNT 
FROM 
    (SELECT 
        SALES_DATE, 
        PRODUCT_ID, 
        USER_ID, 
        SALES_AMOUNT 
     FROM ONLINE_SALE 
     WHERE SALES_DATE LIKE '2022-03-%'
     UNION
     SELECT 
        SALES_DATE, 
        PRODUCT_ID, 
        NULL AS USER_ID, 
        SALES_AMOUNT 
     FROM OFFLINE_SALE 
     WHERE SALES_DATE LIKE '2022-03-%') AS combined_sales
     ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;