# -- 년 월 성별별로 상품을 구매한 회원 수
# SELECT 
#     YEAR(os.SALES_DATE) AS YEAR,
#     MONTH(os.SALES_DATE) AS MONTH, 
#     ui.GENDER,
#     COUNT(ui.USER_ID) AS USERS
# FROM ONLINE_SALE os
# JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
# WHERE ui.GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, GENDER
# ORDER BY YEAR, MONTH, GENDER;

SELECT 
    YEAR(os.SALES_DATE) AS YEAR,
    MONTH(os.SALES_DATE) AS MONTH, 
    ui.GENDER,
    COUNT(DISTINCT os.USER_ID) AS USERS
FROM ONLINE_SALE os
JOIN USER_INFO ui ON os.USER_ID = ui.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;