# SELECT 
# FROM ONLINE_SALE
# WHERE ONLINE_SALE_ID

SELECT YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT USER_ID) as PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER_ID)/(
        SELECT COUNT(1)-- 21년 가입한 회원의 수
        FROM USER_INFO
        WHERE YEAR(JOINED) =2021 ), 1) as PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN 
    (SELECT USER_ID -- 21년 가입한 회원의 수
    FROM USER_INFO
    WHERE JOINED BETWEEN 20210101 AND 20211231)
GROUP BY (MONTH)
ORDER BY YEAR, MONTH


# SELECT COUNT(1)-- 21년 가입한 회원의 수
# FROM USER_INFO
# WHERE JOINED BETWEEN 20210101 AND 20211231
