SELECT 
    CAR_ID,
    IF(COUNT(*) = 0, '대여 가능', '대여중') AS AVAILABILITY
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    '2022-10-16' BETWEEN START_DATE AND END_DATE
GROUP BY 
    CAR_ID
UNION
SELECT 
    CAR_ID,
    '대여 가능' AS AVAILABILITY
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 
    CAR_ID NOT IN (
        SELECT 
            CAR_ID 
        FROM 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE 
            '2022-10-16' BETWEEN START_DATE AND END_DATE
    )
ORDER BY 
    CAR_ID DESC;