WITH TRUCK_RENTAL AS (
    SELECT h.HISTORY_ID, c.DAILY_FEE, 
           DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS RENTAL_DAYS,
           CASE
               WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN dp.DISCOUNT_RATE
               WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN dp.DISCOUNT_RATE
               WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN dp.DISCOUNT_RATE
               ELSE 0
           END AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp 
           ON c.CAR_TYPE = dp.CAR_TYPE 
           AND (
               (DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 AND dp.DURATION_TYPE = '90일 이상') OR
               (DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 90 AND dp.DURATION_TYPE = '30일 이상') OR
               (DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 AND DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 30 AND dp.DURATION_TYPE = '7일 이상')
           )
    WHERE c.CAR_TYPE = '트럭'
)
SELECT HISTORY_ID, 
       FLOOR(DAILY_FEE * RENTAL_DAYS * (1 - (DISCOUNT_RATE / 100))) AS FEE
FROM TRUCK_RENTAL
ORDER BY FEE DESC, HISTORY_ID DESC;