SELECT
    FLAVOR
FROM
    (
        SELECT
            FIRST_HALF.FLAVOR,
            SUM(FIRST_HALF.TOTAL_ORDER) AS FIRST_HALF_TOTAL,
            COALESCE(SUM(JULY.TOTAL_ORDER), 0) AS JULY_TOTAL,
            SUM(FIRST_HALF.TOTAL_ORDER) + COALESCE(SUM(JULY.TOTAL_ORDER), 0) AS TOTAL_ORDER
        FROM
            FIRST_HALF
            LEFT JOIN JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
        GROUP BY
            FIRST_HALF.FLAVOR
    ) AS combined_orders
ORDER BY
    TOTAL_ORDER DESC
LIMIT 3;