-- 코드를 입력하세요
SELECT b.WRITER_ID as USER_ID,	u.NICKNAME,	b.TOTAL_SALES
FROM USED_GOODS_USER u INNER JOIN 
    (SELECT WRITER_ID, sum(PRICE) as TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000) as b
ON b.WRITER_ID = u.USER_ID
ORDER BY TOTAL_SALES