SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO i
WHERE i.ITEM_ID IN (
    SELECT t.ITEM_ID
    FROM ITEM_TREE t
    WHERE t.PARENT_ITEM_ID IN (
        SELECT i2.ITEM_ID
        FROM ITEM_INFO i2
        WHERE i2.RARITY = 'RARE'
    )
)
ORDER BY i.ITEM_ID DESC;
