# SELECT YEAR,	YEAR_DEV,	ID
# FROM ECOLI_DATA

SELECT t1.YEAR, t2.SIZE_OF_COLONY - t1.SIZE_OF_COLONY  as YEAR_DEV,	t1.ID
FROM (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, SIZE_OF_COLONY, ID
    FROM ECOLI_DATA) t1  JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR) t2 -- 연도별 가장 큰 대장균 크기 테이블
    on t1.YEAR = t2.YEAR
ORDER BY YEAR, YEAR_DEV

# SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, SIZE_OF_COLONY, ID
# FROM ECOLI_DATA
# SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as SIZE_OF_COLONY
# FROM ECOLI_DATA
# GROUP BY YEAR