SELECT t2.ID, t2.FISH_NAME, t2.LENGTH
FROM 
(
SELECT n.FISH_NAME, i.ID, i.LENGTH, i.FISH_TYPE
FROM FISH_INFO i LEFT OUTER JOIN FISH_NAME_INFO n
on n.FISH_TYPE = i.FISH_TYPE
) t2
WHERE (t2.FISH_TYPE, t2.LENGTH) IN 
    (SELECT i.FISH_TYPE, MAX(i.LENGTH) as LENGTH 
    FROM FISH_INFO i INNER JOIN FISH_NAME_INFO n
    ON n.FISH_TYPE = i.FISH_TYPE
    GROUP BY n.FISH_TYPE)
ORDER BY t2.ID;

# # SELECT *
# # FROM FISH_INFO i LEFT OUTER JOIN FISH_NAME_INFO n
# # on n.FISH_NAME = i.FISH_TYPE