SELECT n.FISH_NAME, MAX(i.LENGTH), i.ID
FROM FISH_INFO i INNER JOIN FISH_NAME_INFO n
ON n.FISH_NAME = i.FISH_TYPE
GROUP BY n.FISH_NAME

# GROUP BY n.FISH_NAME
# ORDER BY i.ID;

# SELECT *
# FROM FISH_INFO i LEFT OUTER JOIN FISH_NAME_INFO n
# on n.FISH_NAME = i.FISH_TYPE