SELECT gr.SCORE,	em.EMP_NO,	em.EMP_NAME,	em.POSITION,	em.EMAIL
FROM HR_EMPLOYEES em LEFT OUTER JOIN (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO) gr
ON em.EMP_NO = gr.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;