SELECT av.DEPT_ID,	hr.DEPT_NAME_EN, av.AVG_SAL
FROM (SELECT DEPT_ID, ROUND(AVG(SAL),0) AVG_SAL
    FROM HR_EMPLOYEES em
    GROUP BY DEPT_ID) av LEFT OUTER JOIN  HR_DEPARTMENT hr
ON av.DEPT_ID = hr.DEPT_ID
ORDER BY AVG_SAL DESC;