SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) MAX_LENGTH, FISH_TYPE
FROM FISH_INFO 
GROUP BY FISH_TYPE
HAVING AVG(CASE WHEN LENGTH <= 10 or LENGTH is null THEN 10 
           ELSE LENGTH 
           END) >= 33
ORDER BY FISH_TYPE